const Projects = {
  games: [
    {
      id: "minesweeper",
      title: "minesweeper_title",
      description: "minesweeper_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241201_ai_gallery_minesweeper_small.png",
      link: "/games/minesweeper",
    },
    {
      id: "sliding",
      title: "sliding_title",
      description: "sliding_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_sliding_small.png",
      link: "/games/sliding",
    },
    {
      id: "sokoban",
      title: "sokoban_title",
      description: "sokoban_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241116_ai_gallery_sokoban_small.png",
      link: "/games/sokoban",
    },
    {
      id: "lasermaze",
      title: "lasermaze_title",
      description: "lasermaze_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20251011_ai_gallery_lasermaze.webp",
      link: "/games/lasermaze",
    },
    {
      id: "unblockme",
      title: "unblockme_title",
      description: "unblockme_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250924_ai_gallery_unblockme_small.webp",
      link: "/games/unblockme",
    },
    {
      id: "sudoku",
      title: "sudoku_title",
      description: "sudoku_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_sudoku_small.png",
      link: "/games/sudoku",
    },
    {
      id: "maze",
      title: "maze_title",
      description: "maze_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241201_ai_gallery_maze_small.png",
      link: "/games/maze",
    },
    {
      id: "tangram",
      title: "tangram_title",
      description: "tangram_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250516_ai_gallery_tangram.webp",
      link: "/games/tangram",
    },
    {
      id: "gomoku",
      title: "gomoku_title",
      description: "gomoku_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_gomoku_small.png",
      link: "/games/gomoku",
    },
    {
      id: "cube",
      title: "cube_title",
      description: "cube_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_cube_small.png",
      link: "/games/cube",
    },
    {
      id: "tetris",
      title: "tetris_title",
      description: "tetris_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_tetris_small.png",
      link: "/games/tetris",
    },
    {
      id: "snake",
      title: "snake_title",
      description: "snake_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_snake_small.png",
      link: "/games/snake",
    },
    {
      id: "2048",
      title: "2048_title",
      description: "2048_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_2048_small.png",
      link: "/games/2048",
    },
    {
      id: "chess",
      title: "chess_title",
      description: "chess_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241031_ai_gallery_2048_chess.png",
      link: "/games/chess",
    },
  ],
  algorithms: [
    {
      id: "heap",
      slug: "heap",
      title: "heap_title",
      description: "heap_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_heapv2.gif",
      link: "/algorithms/heap/",
    },
    {
      id: "hanoitower",
      slug: "hanoitower",
      title: "hanoitower_title",
      description: "hanoitower_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240812_ai_gallery_hanoitower.webp",
      link: "/algorithms/hanoitower/",
    },
    {
      id: "hashtable",
      slug: "hashtable",
      title: "hashtable_title",
      description: "hashtable_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_hashtable.webp",
      link: "/algorithms/hashtable/",
    },
    {
      id: "dpcoin",
      slug: "dpcoin",
      title: "dpcoin_title",
      description: "dpcoin_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240730_ai_gallery_dpcoin.webp",
      link: "/algorithms/dpcoin/",
    },
    {
      id: "trie",
      slug: "trie",
      title: "trie_title",
      description: "trie_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_trie.webp",
      link: "/algorithms/trie/",
    },
    {
      id: "binarysearchtree",
      slug: "binarysearchtree",
      title: "binarysearchtree_title",
      description: "binarysearchtree_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240908_ai_gallery_binarysearchtree.webp",
      link: "/algorithms/binarysearchtree/",
    },
    {
      id: "bloomfilter",
      slug: "bloomfilter",
      title: "bloomfilter_title",
      description: "bloomfilter_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240805_ai_gallery_bloomfilter.webp",
      link: "/algorithms/bloomfilter/",
    },
    {
      id: "dijkstra",
      slug: "dijkstra",
      title: "dijkstra_title",
      description: "dijkstra_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240709_ai_gallery_dijkstra_v3.gif",
      link: "/algorithms/dijkstra/",
    },
    {
      id: "stack",
      slug: "stack",
      title: "stack_title",
      description: "stack_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_stack.webp",
      link: "/algorithms/stack/",
    },
    {
      id: "hashring",
      slug: "hashring",
      title: "hashring_title",
      description: "hashring_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240801_ai_gallery_hashring.webp",
      link: "/algorithms/hashring/",
    },
    {
      id: "jumphash",
      slug: "jumphash",
      title: "jumphash_title",
      description: "jumphash_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240809_ai_gallery_jumphash.webp",
      link: "/algorithms/jumphash/",
    },
    {
      id: "skiplist",
      slug: "skiplist",
      title: "skiplist_title",
      description: "skiplist_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240728_ai_gallery_skiplist.webp",
      link: "/algorithms/skiplist/",
    },
    {
      id: "astar",
      slug: "astar",
      title: "astar_title",
      description: "astar_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_astar_path.gif",
      link: "/algorithms/astar/",
    },
    {
      id: "bfs_path",
      slug: "bfs_path",
      title: "bfs_path_title",
      description: "bfs_path_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_bfs_path.gif",
      link: "/algorithms/bfs_path/",
    },
    {
      id: "linkedlist",
      slug: "linkedlist",
      title: "linkedlist_title",
      description: "linkedlist_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_linkedlist.webp",
      link: "/algorithms/linkedlist/",
    },
    {
      id: "ratelimit",
      slug: "ratelimit",
      title: "ratelimit_title",
      description: "ratelimit_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240716_ai_gallery_ratelimit.gif",
      link: "/algorithms/ratelimit/",
    },
    {
      id: "tokenbucket",
      slug: "tokenbucket",
      title: "tokenbucket_title",
      description: "tokenbucket_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_tokenbucket.webp",
      link: "/algorithms/tokenbucket/",
    },
    {
      id: "intervalscheduling",
      slug: "intervalscheduling",
      title: "intervalscheduling_title",
      description: "intervalscheduling_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202025-11-26%20134142.png",
      link: "/algorithms/intervalscheduling/",
    },
    {
      id: "minimumspanningtree",
      slug: "minimumspanningtree",
      title: "minimumspanningtree_title",
      description: "minimumspanningtree_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202025-11-26%20134131.png",
      link: "/algorithms/minimumspanningtree/",
    },
    // Placeholders for upcoming algorithms
    {
      id: "nqueens",
      slug: "nqueens",
      title: "N-Queens Problem",
      description: "Placeholder: N-Queens backtracking visualization",
      image: "/logo512.png",
      link: "/algorithms/nqueens/",
    },
    {
      id: "knightstour",
      slug: "knightstour",
      title: "Knight's Tour Problem",
      description: "Placeholder: Knight's Tour backtracking visualization",
      image: "/logo512.png",
      link: "/algorithms/knightstour/",
    },
    {
      id: "depthlimitedsearch",
      slug: "depthlimitedsearch",
      title: "Depth-Limited Search",
      description: "Placeholder: Depth-limited search demonstration",
      image: "/logo512.png",
      link: "/algorithms/depthlimitedsearch/",
    },
    {
      id: "bubblesort",
      slug: "bubblesort",
      title: "Bubble Sort",
      description: "Placeholder: Bubble sort visualization",
      image: "/logo512.png",
      link: "/algorithms/bubblesort/",
    },
    {
      id: "quicksort",
      slug: "quicksort",
      title: "Quicksort",
      description: "Placeholder: Quicksort divide-and-conquer visualization",
      image: "/logo512.png",
      link: "/algorithms/quicksort/",
    },
    {
      id: "floydwarshall",
      slug: "floydwarshall",
      title: "Floyd-Warshall Shortest Paths",
      description: "Placeholder: Floyd-Warshall dynamic programming visualization",
      image: "/logo512.png",
      link: "/algorithms/floydwarshall/",
    },
    {
      id: "factorial",
      slug: "factorial",
      title: "Nth Factorial",
      description: "Placeholder: Simple recursive factorial demonstration",
      image: "/logo512.png",
      link: "/algorithms/factorial/",
    },
  ],
  tools: [
    {
      id: "gendocx",
      title: "gendocx_title",
      description: "gendocx_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20241030_ai_gallery_gendocx.webp",
      link: "/tools/gendocx/",
    },
    {
      id: "mergeword",
      title: "mergeword_title",
      description: "mergeword_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250704_ai_gallery_mergetool.webp",
      link: "/tools/mergeword/",
    },
    {
      id: "retire",
      title: "retire_title",
      description: "retire_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250327_ai_gallery_retire.png",
      link: "/tools/retire/",
    },
    {
      id: "loanrate",
      title: "loanrate_title",
      description: "loanrate_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20250428_ai_gallery_loanrate_en.webp",
      link: "/tools/loanrate/",
    },
    {
      id: "chartrace",
      title: "chartrace_title",
      description: "chartrace_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240928_ai_gallery_chartrace_cover.webp",
      link: "/tools/chartrace/",
    },
    {
      id: "subtitles",
      title: "subtitles_title",
      description: "subtitles_description",
      image: "https://slefboot-1251736664.file.myqcloud.com/20240728_ai_gallery_subtitles.webp",
      link: "/tools/subtitles/",
    },
    {
      id: "elibrary",
      title: "E-Library UI",
      description: "Demo E-Library interface built with React + Tailwind",
      image: "/logo512.png",
      link: "/tools/elibrary/",
    },
  ],
};

export default Projects;
