const Projects = {
  algorithms: [
    {
      id: "heap",
      slug: "heap",
      title: "heap_title",
      description: "heap_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_heapv2.gif",
      link: "/algorithms/heap/",
    },
    {
      id: "hanoitower",
      slug: "hanoitower",
      title: "hanoitower_title",
      description: "hanoitower_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240812_ai_gallery_hanoitower.webp",
      link: "/algorithms/hanoitower/",
    },
    {
      id: "hashtable",
      slug: "hashtable",
      title: "hashtable_title",
      description: "hashtable_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_hashtable.webp",
      link: "/algorithms/hashtable/",
    },
    {
      id: "dpcoin",
      slug: "dpcoin",
      title: "dpcoin_title",
      description: "dpcoin_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240730_ai_gallery_dpcoin.webp",
      link: "/algorithms/dpcoin/",
    },
    {
      id: "trie",
      slug: "trie",
      title: "trie_title",
      description: "trie_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_trie.webp",
      link: "/algorithms/trie/",
    },
    {
      id: "binarysearchtree",
      slug: "binarysearchtree",
      title: "binarysearchtree_title",
      description: "binarysearchtree_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240908_ai_gallery_binarysearchtree.webp",
      link: "/algorithms/binarysearchtree/",
    },
    {
      id: "bloomfilter",
      slug: "bloomfilter",
      title: "bloomfilter_title",
      description: "bloomfilter_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240805_ai_gallery_bloomfilter.webp",
      link: "/algorithms/bloomfilter/",
    },
    {
      id: "dijkstra",
      slug: "dijkstra",
      title: "dijkstra_title",
      description: "dijkstra_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240709_ai_gallery_dijkstra_v3.gif",
      link: "/algorithms/dijkstra/",
    },
    {
      id: "stack",
      slug: "stack",
      title: "stack_title",
      description: "stack_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_stack.webp",
      link: "/algorithms/stack/",
    },
    {
      id: "hashring",
      slug: "hashring",
      title: "hashring_title",
      description: "hashring_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240801_ai_gallery_hashring.webp",
      link: "/algorithms/hashring/",
    },
    {
      id: "jumphash",
      slug: "jumphash",
      title: "jumphash_title",
      description: "jumphash_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240809_ai_gallery_jumphash.webp",
      link: "/algorithms/jumphash/",
    },
    {
      id: "skiplist",
      slug: "skiplist",
      title: "skiplist_title",
      description: "skiplist_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240728_ai_gallery_skiplist.webp",
      link: "/algorithms/skiplist/",
    },
    {
      id: "astar",
      slug: "astar",
      title: "astar_title",
      description: "astar_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_astar_path.gif",
      link: "/algorithms/astar/",
    },
    {
      id: "bfs_path",
      slug: "bfs_path",
      title: "bfs_path_title",
      description: "bfs_path_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240706_ai_gallery_bfs_path.gif",
      link: "/algorithms/bfs_path/",
    },
    {
      id: "linkedlist",
      slug: "linkedlist",
      title: "linkedlist_title",
      description: "linkedlist_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_linkedlist.webp",
      link: "/algorithms/linkedlist/",
    },
    {
      id: "ratelimit",
      slug: "ratelimit",
      title: "ratelimit_title",
      description: "ratelimit_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240716_ai_gallery_ratelimit.gif",
      link: "/algorithms/ratelimit/",
    },
    {
      id: "tokenbucket",
      slug: "tokenbucket",
      title: "tokenbucket_title",
      description: "tokenbucket_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/20240726_ai_gallery_tokenbucket.webp",
      link: "/algorithms/tokenbucket/",
    },
    {
      id: "intervalscheduling",
      slug: "intervalscheduling",
      title: "intervalscheduling_title",
      description: "intervalscheduling_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202025-11-26%20134142.png",
      link: "/algorithms/intervalscheduling/",
    },
    {
      id: "minimumspanningtree",
      slug: "minimumspanningtree",
      title: "minimumspanningtree_title",
      description: "minimumspanningtree_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202025-11-26%20134131.png",
      link: "/algorithms/minimumspanningtree/",
    },
    {
      id: "nqueens",
      slug: "nqueens",
      title: "nqueens_title",
      description: "nqueens_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/nqueen.gif",
      link: "/algorithms/nqueens/",
    },
    {
      id: "knightstour",
      slug: "knightstour",
      title: "knightstour_title",
      description: "knightstour_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/knights.gif",
      link: "/algorithms/knightstour/",
    },
    {
      id: "depthlimitedsearch",
      slug: "depthlimitedsearch",
      title: "depthlimitedsearch_title",
      description: "depthlimitedsearch_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/DFS.gif",
      link: "/algorithms/depthlimitedsearch/",
    },
    {
      id: "bubblesort",
      slug: "bubblesort",
      title: "bubblesort_title",
      description: "bubblesort_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/bubblesort.gif",
      link: "/algorithms/bubblesort/",
    },
    {
      id: "quicksort",
      slug: "quicksort",
      title: "quicksort_title",
      description: "quicksort_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/quicksort.gif",
      link: "/algorithms/quicksort/",
    },
    {
      id: "floydwarshall",
      slug: "floydwarshall",
      title: "floydwarshall_title",
      description: "floydwarshall_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/floyd.gif",
      link: "/algorithms/floydwarshall/",
    },
    {
      id: "factorial",
      slug: "factorial",
      title: "factorial_title",
      description: "factorial_description",
      image: "https://xiaohashu-jing.oss-cn-nanjing.aliyuncs.com/factorial.gif",
      link: "/algorithms/factorial/",
    },
  ],
};

export default Projects;
